endpoint: create server action via hook
This is actually a trick to work around this error:

  psycopg2.IntegrityError: null value in column "activity_user_type"
  violates not-null constraint

which happens when `mail` is installed,
since it adds this field as required in DB.

We DO NOT want to depend on mail for this problem...
hence, here we go with this crazy dance :S

Moreover, we are forced to use a query for this
because if you use `model.create` you get

  ValueError: Invalid field 'activity_user_type' on model 'ir.actions.server'

because the field is not yet in the env if the mail modules is not loaded 1st.